-- Currency Seeder
-- Insert common world currencies

INSERT INTO currencies (id, code, name, symbol, "decimalPlaces", "isActive", "createdAt", "updatedAt") VALUES
-- Major Reserve Currencies
('cur_001', 'USD', 'US Dollar', '$', 2, true, NOW(), NOW()),
('cur_002', 'EUR', 'Euro', '€', 2, true, NOW(), NOW()),
('cur_003', 'GBP', 'British Pound', '£', 2, true, NOW(), NOW()),
('cur_004', 'JPY', 'Japanese Yen', '¥', 0, true, NOW(), NOW()),
('cur_005', 'CHF', 'Swiss Franc', 'CHF', 2, true, NOW(), NOW()),
('cur_006', 'CAD', 'Canadian Dollar', 'C$', 2, true, NOW(), NOW()),
('cur_007', 'AUD', 'Australian Dollar', 'A$', 2, true, NOW(), NOW()),
('cur_008', 'CNY', 'Chinese Yuan', '¥', 2, true, NOW(), NOW()),

-- European Currencies
('cur_009', 'SEK', 'Swedish Krona', 'kr', 2, true, NOW(), NOW()),
('cur_010', 'NOK', 'Norwegian Krone', 'kr', 2, true, NOW(), NOW()),
('cur_011', 'DKK', 'Danish Krone', 'kr', 2, true, NOW(), NOW()),
('cur_012', 'PLN', 'Polish Złoty', 'zł', 2, true, NOW(), NOW()),
('cur_013', 'CZK', 'Czech Koruna', 'Kč', 2, true, NOW(), NOW()),
('cur_014', 'HUF', 'Hungarian Forint', 'Ft', 0, true, NOW(), NOW()),
('cur_015', 'RON', 'Romanian Leu', 'lei', 2, true, NOW(), NOW()),
('cur_016', 'BGN', 'Bulgarian Lev', 'лв', 2, true, NOW(), NOW()),
('cur_017', 'HRK', 'Croatian Kuna', 'kn', 2, true, NOW(), NOW()),
('cur_018', 'RSD', 'Serbian Dinar', 'дин', 2, true, NOW(), NOW()),
('cur_019', 'UAH', 'Ukrainian Hryvnia', '₴', 2, true, NOW(), NOW()),
('cur_020', 'RUB', 'Russian Ruble', '₽', 2, true, NOW(), NOW()),
('cur_021', 'TRY', 'Turkish Lira', '₺', 2, true, NOW(), NOW()),
('cur_022', 'ILS', 'Israeli Shekel', '₪', 2, true, NOW(), NOW()),

-- Asian Currencies
('cur_023', 'KRW', 'South Korean Won', '₩', 0, true, NOW(), NOW()),
('cur_024', 'SGD', 'Singapore Dollar', 'S$', 2, true, NOW(), NOW()),
('cur_025', 'HKD', 'Hong Kong Dollar', 'HK$', 2, true, NOW(), NOW()),
('cur_026', 'TWD', 'Taiwan Dollar', 'NT$', 2, true, NOW(), NOW()),
('cur_027', 'THB', 'Thai Baht', '฿', 2, true, NOW(), NOW()),
('cur_028', 'MYR', 'Malaysian Ringgit', 'RM', 2, true, NOW(), NOW()),
('cur_029', 'IDR', 'Indonesian Rupiah', 'Rp', 0, true, NOW(), NOW()),
('cur_030', 'PHP', 'Philippine Peso', '₱', 2, true, NOW(), NOW()),
('cur_031', 'VND', 'Vietnamese Dong', '₫', 0, true, NOW(), NOW()),
('cur_032', 'INR', 'Indian Rupee', '₹', 2, true, NOW(), NOW()),
('cur_033', 'PKR', 'Pakistani Rupee', '₨', 2, true, NOW(), NOW()),
('cur_034', 'BDT', 'Bangladeshi Taka', '৳', 2, true, NOW(), NOW()),
('cur_035', 'LKR', 'Sri Lankan Rupee', '₨', 2, true, NOW(), NOW()),
('cur_036', 'NPR', 'Nepalese Rupee', '₨', 2, true, NOW(), NOW()),
('cur_037', 'MMK', 'Myanmar Kyat', 'K', 2, true, NOW(), NOW()),
('cur_038', 'KHR', 'Cambodian Riel', '៛', 2, true, NOW(), NOW()),
('cur_039', 'LAK', 'Lao Kip', '₭', 2, true, NOW(), NOW()),
('cur_040', 'MNT', 'Mongolian Tugrik', '₮', 2, true, NOW(), NOW()),

-- Middle Eastern & African Currencies
('cur_041', 'AED', 'UAE Dirham', 'د.إ', 2, true, NOW(), NOW()),
('cur_042', 'SAR', 'Saudi Riyal', 'ر.س', 2, true, NOW(), NOW()),
('cur_043', 'QAR', 'Qatari Riyal', 'ر.ق', 2, true, NOW(), NOW()),
('cur_044', 'KWD', 'Kuwaiti Dinar', 'د.ك', 3, true, NOW(), NOW()),
('cur_045', 'BHD', 'Bahraini Dinar', '.د.ب', 3, true, NOW(), NOW()),
('cur_046', 'OMR', 'Omani Rial', 'ر.ع.', 3, true, NOW(), NOW()),
('cur_047', 'JOD', 'Jordanian Dinar', 'د.ا', 3, true, NOW(), NOW()),
('cur_048', 'EGP', 'Egyptian Pound', 'E£', 2, true, NOW(), NOW()),
('cur_049', 'MAD', 'Moroccan Dirham', 'د.م.', 2, true, NOW(), NOW()),
('cur_050', 'TND', 'Tunisian Dinar', 'د.ت', 3, true, NOW(), NOW()),
('cur_051', 'DZD', 'Algerian Dinar', 'د.ج', 2, true, NOW(), NOW()),
('cur_052', 'LYD', 'Libyan Dinar', 'ل.د', 3, true, NOW(), NOW()),
('cur_053', 'SDG', 'Sudanese Pound', 'ج.س.', 2, true, NOW(), NOW()),
('cur_054', 'NGN', 'Nigerian Naira', '₦', 2, true, NOW(), NOW()),
('cur_055', 'GHS', 'Ghanaian Cedi', '₵', 2, true, NOW(), NOW()),
('cur_056', 'KES', 'Kenyan Shilling', 'KSh', 2, true, NOW(), NOW()),
('cur_057', 'UGX', 'Ugandan Shilling', 'USh', 0, true, NOW(), NOW()),
('cur_058', 'TZS', 'Tanzanian Shilling', 'TSh', 0, true, NOW(), NOW()),
('cur_059', 'ZAR', 'South African Rand', 'R', 2, true, NOW(), NOW()),
('cur_060', 'NAD', 'Namibian Dollar', 'N$', 2, true, NOW(), NOW()),
('cur_061', 'BWP', 'Botswana Pula', 'P', 2, true, NOW(), NOW()),
('cur_062', 'ZMW', 'Zambian Kwacha', 'ZK', 2, true, NOW(), NOW()),
('cur_063', 'MWK', 'Malawian Kwacha', 'MK', 2, true, NOW(), NOW()),
('cur_064', 'MZN', 'Mozambican Metical', 'MT', 2, true, NOW(), NOW()),
('cur_065', 'MUR', 'Mauritian Rupee', '₨', 2, true, NOW(), NOW()),
('cur_066', 'SCR', 'Seychellois Rupee', '₨', 2, true, NOW(), NOW()),
('cur_067', 'KMF', 'Comorian Franc', 'CF', 0, true, NOW(), NOW()),
('cur_068', 'DJF', 'Djiboutian Franc', 'Fdj', 0, true, NOW(), NOW()),
('cur_069', 'ETB', 'Ethiopian Birr', 'Br', 2, true, NOW(), NOW()),
('cur_070', 'SOS', 'Somali Shilling', 'Sh.So.', 0, true, NOW(), NOW()),
('cur_071', 'RWF', 'Rwandan Franc', 'FRw', 0, true, NOW(), NOW()),
('cur_072', 'BIF', 'Burundian Franc', 'FBu', 0, true, NOW(), NOW()),
('cur_073', 'CDF', 'Congolese Franc', 'FC', 2, true, NOW(), NOW()),
('cur_074', 'XAF', 'Central African CFA Franc', 'FCFA', 0, true, NOW(), NOW()),
('cur_075', 'XOF', 'West African CFA Franc', 'CFA', 0, true, NOW(), NOW()),
('cur_076', 'XPF', 'CFP Franc', '₣', 0, true, NOW(), NOW()),

-- Americas Currencies
('cur_077', 'MXN', 'Mexican Peso', '$', 2, true, NOW(), NOW()),
('cur_078', 'BRL', 'Brazilian Real', 'R$', 2, true, NOW(), NOW()),
('cur_079', 'ARS', 'Argentine Peso', '$', 2, true, NOW(), NOW()),
('cur_080', 'CLP', 'Chilean Peso', '$', 0, true, NOW(), NOW()),
('cur_081', 'COP', 'Colombian Peso', '$', 2, true, NOW(), NOW()),
('cur_082', 'PEN', 'Peruvian Sol', 'S/', 2, true, NOW(), NOW()),
('cur_083', 'UYU', 'Uruguayan Peso', '$U', 2, true, NOW(), NOW()),
('cur_084', 'PYG', 'Paraguayan Guaraní', '₲', 0, true, NOW(), NOW()),
('cur_085', 'BOB', 'Bolivian Boliviano', 'Bs.', 2, true, NOW(), NOW()),
('cur_086', 'GTQ', 'Guatemalan Quetzal', 'Q', 2, true, NOW(), NOW()),
('cur_087', 'HNL', 'Honduran Lempira', 'L', 2, true, NOW(), NOW()),
('cur_088', 'NIO', 'Nicaraguan Córdoba', 'C$', 2, true, NOW(), NOW()),
('cur_089', 'CRC', 'Costa Rican Colón', '₡', 2, true, NOW(), NOW()),
('cur_090', 'PAB', 'Panamanian Balboa', 'B/.', 2, true, NOW(), NOW()),
('cur_091', 'DOP', 'Dominican Peso', 'RD$', 2, true, NOW(), NOW()),
('cur_092', 'JMD', 'Jamaican Dollar', 'J$', 2, true, NOW(), NOW()),
('cur_093', 'TTD', 'Trinidad and Tobago Dollar', 'TT$', 2, true, NOW(), NOW()),
('cur_094', 'BBD', 'Barbadian Dollar', 'Bds$', 2, true, NOW(), NOW()),
('cur_095', 'XCD', 'East Caribbean Dollar', 'EC$', 2, true, NOW(), NOW()),
('cur_096', 'GYD', 'Guyanese Dollar', 'G$', 2, true, NOW(), NOW()),
('cur_097', 'SRD', 'Surinamese Dollar', '$', 2, true, NOW(), NOW()),
('cur_098', 'VES', 'Venezuelan Bolívar', 'Bs.', 2, true, NOW(), NOW()),
('cur_099', 'CUP', 'Cuban Peso', '$', 2, true, NOW(), NOW()),
('cur_100', 'HTG', 'Haitian Gourde', 'G', 2, true, NOW(), NOW()),

-- Oceania Currencies
('cur_101', 'NZD', 'New Zealand Dollar', 'NZ$', 2, true, NOW(), NOW()),
('cur_102', 'FJD', 'Fijian Dollar', 'FJ$', 2, true, NOW(), NOW()),
('cur_103', 'PGK', 'Papua New Guinean Kina', 'K', 2, true, NOW(), NOW()),
('cur_104', 'SBD', 'Solomon Islands Dollar', 'SI$', 2, true, NOW(), NOW()),
('cur_105', 'VUV', 'Vanuatu Vatu', 'VT', 0, true, NOW(), NOW()),
('cur_106', 'WST', 'Samoan Tālā', 'T', 2, true, NOW(), NOW()),
('cur_107', 'TOP', 'Tongan Paʻanga', 'T$', 2, true, NOW(), NOW()),
('cur_108', 'KID', 'Kiribati Dollar', '$', 2, true, NOW(), NOW()),
('cur_109', 'TVD', 'Tuvaluan Dollar', '$', 2, true, NOW(), NOW()),
('cur_110', 'XPF', 'CFP Franc', '₣', 0, true, NOW(), NOW()),

-- Special Cases
('cur_111', 'BTC', 'Bitcoin', '₿', 8, true, NOW(), NOW()),
('cur_112', 'ETH', 'Ethereum', 'Ξ', 18, true, NOW(), NOW()),
('cur_113', 'USDT', 'Tether', '₮', 2, true, NOW(), NOW()),
('cur_114', 'USDC', 'USD Coin', '$', 2, true, NOW(), NOW()),
('cur_115', 'BNB', 'Binance Coin', 'BNB', 8, true, NOW(), NOW());
